networks:
  instareddit-network:
    driver: bridge
services:
  frontend:
    image: node:latest
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - instareddit-network
    environment:
      - NODE_ENV=development
  backend:
    build: backend
    command: > 
      sh -c "python instareddit/manage.py makemigrations &&
          python instareddit/manage.py migrate &&
          python instareddit/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      PORT: "8000"
      DJANGO_DEBUG: "FALSE"
    volumes:
        - ./backend:/usr/src/app
    networks:
      - instareddit-network
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mariadb:latest
    restart: always
    networks:
      - instareddit-network
    volumes:
      - instareddit-db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_ROOT_HOST=%
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - instareddit-network

 
  
volumes:
  instareddit-db:  
