networks:
  instareddit-network:
    driver: bridge
services:
  frontend:
    image: node:latest
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - instareddit-network
  backend:
    build: backend
    command: "python -m gunicorn --chdir instareddit/ instareddit.asgi:application -k uvicorn.workers.UvicornWorker"
    ports:
      - 8000:8000
    environment:
      PORT: "8000"
      RENDER: "TRUE"
    volumes:
        - ./backend:/usr/src/app
    networks:
      - instareddit-network
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    networks:
      - instareddit-network
    volumes:
      - instareddit-db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=secret

 
  
volumes:
  instareddit-db:  
