services:
  - type: web
    plan: free
    name: instareddit
    runtime: python
    buildCommand: "./render-build.sh"
    repo: https://github.com/UndecidedCS4800/instareddit.git
    startCommand: "python -m gunicorn --chdir backend/instareddit instareddit.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true