# Generated by Django 5.1 on 2024-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(db_table='friendship', to='api.user'),
        ),
    ]
