# Generated by Django 5.1 on 2024-09-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dummy_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
