# Generated by Django 5.1 on 2024-09-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
