# Generated by Django 5.1 on 2024-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
