# Generated by Django 5.1 on 2024-09-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_community_picture_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
