# Generated by Django 5.1 on 2024-09-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('password_hash', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
